"""
Daily Compound Interest calculation engine.

A faithful reimplementation of the standalone "Daily Compound Calculator"
Flutter app's CompoundInterestEngine. That app's source code is lost; this
port is built from its surviving documentation
(D:\\Claude\\Documentation\\daily_compound_calculator_Documentation,
particularly 02_TDD section 3), which was itself generated by reading the
original lib/services/compound_interest_engine.dart source before it was
lost. Every algorithmic decision below traces to that document rather
than a textbook compound-interest formula:

- The configured rate is applied IN FULL on every compounding date — it
  is NOT divided by periods-per-year or treated as an annualized rate.
  A "1% monthly" scenario multiplies the balance by 1.01 each month it
  fires, not by (1 + 0.01/12) each day.
- Interest is never rounded during computation — only at display time.
- A calendar day with no compounding event still gets a schedule row
  (opening == closing, zero interest) so a day-wise view shows every
  day, not only compounding days.
- A hard magnitude safety cap stops schedule generation once a day's
  closing balance exceeds it — the engine truncates the schedule rather
  than raising or overflowing, and reports that it did so.
"""
from __future__ import annotations

import calendar
from dataclasses import dataclass, field
from datetime import date, timedelta

# Absolute ceiling regardless of caller input. The original app derived
# this from its currency formatter's own limitation; kept here for
# behavioral parity (this is the point at which real-world scenarios
# have long since stopped being meaningful anyway).
MAX_RESULT_MAGNITUDE = 1e21

_FREQUENCY_STEP_MONTHS = {
    "monthly": 1,
    "quarterly": 3,
    "half_yearly": 6,
    "yearly": 12,
}

VALID_DURATION_UNITS = {"days", "months", "years"}
VALID_FREQUENCIES = {"daily", "weekly", "monthly", "quarterly", "half_yearly", "yearly"}


def _add_months(d: date, months: int) -> date:
    """Calendar-accurate month addition, clamped to the target month's
    actual last day (e.g. Jan 31 + 1 month = Feb 28 in a non-leap year).
    Mirrors the original app's documented _addMonths helper exactly."""
    total_month = d.month - 1 + months
    year = d.year + total_month // 12
    month = total_month % 12 + 1
    last_day = calendar.monthrange(year, month)[1]
    return date(year, month, min(d.day, last_day))


def _end_date_and_total_days(start_date: date, duration_value: int, duration_unit: str) -> tuple[date, int]:
    if duration_unit == "days":
        end = start_date + timedelta(days=duration_value)
        total_days = duration_value
    elif duration_unit == "months":
        end = _add_months(start_date, duration_value)
        total_days = (end - start_date).days
    elif duration_unit == "years":
        end = _add_months(start_date, duration_value * 12)
        total_days = (end - start_date).days
    else:
        raise ValueError(f"Unknown duration_unit: {duration_unit!r}")
    return end, total_days


def _compounding_day_offsets(start_date: date, total_days: int, frequency: str) -> set[int]:
    """1-indexed day offsets from start_date on which interest applies.

    Daily: every day. Weekly: every 7th day, plus the final day if the
    last multiple of 7 doesn't land on it exactly. Monthly/Quarterly/
    Half-Yearly/Yearly: calendar-accurate month stepping from
    start_date (each candidate computed fresh from start_date, not
    chained off the previous one, so clamping in one period never drifts
    later periods), plus the final day if the last computed date doesn't
    land on it exactly — all as documented in 02_TDD table 4.
    """
    if total_days <= 0:
        return set()

    if frequency == "daily":
        return set(range(1, total_days + 1))

    if frequency == "weekly":
        offsets = set(range(7, total_days + 1, 7))
        if not offsets or max(offsets) != total_days:
            offsets.add(total_days)
        return offsets

    step = _FREQUENCY_STEP_MONTHS.get(frequency)
    if step is None:
        raise ValueError(f"Unknown frequency: {frequency!r}")

    offsets: set[int] = set()
    k = 1
    while True:
        candidate = _add_months(start_date, k * step)
        offset = (candidate - start_date).days
        if offset > total_days:
            break
        offsets.add(offset)
        k += 1
    if not offsets or max(offsets) != total_days:
        offsets.add(total_days)
    return offsets


@dataclass
class DailyEntry:
    day: int
    entry_date: date
    opening_balance: float
    interest_earned: float
    closing_balance: float
    cumulative_interest: float

    def to_dict(self) -> dict:
        return {
            "day": self.day,
            "date": self.entry_date.isoformat(),
            "opening_balance": self.opening_balance,
            "interest_earned": self.interest_earned,
            "closing_balance": self.closing_balance,
            "cumulative_interest": self.cumulative_interest,
        }


@dataclass
class PeriodEntry:
    period_start: date
    period_end: date
    opening_balance: float
    interest_earned: float
    closing_balance: float
    cumulative_interest: float

    def to_dict(self) -> dict:
        return {
            "period_start": self.period_start.isoformat(),
            "period_end": self.period_end.isoformat(),
            "opening_balance": self.opening_balance,
            "interest_earned": self.interest_earned,
            "closing_balance": self.closing_balance,
            "cumulative_interest": self.cumulative_interest,
        }


@dataclass
class CalculationResult:
    final_amount: float
    total_interest: float
    truncated: bool
    end_date: date
    total_days_requested: int
    daily_schedule: list[DailyEntry] = field(default_factory=list)
    monthly_schedule: list[PeriodEntry] = field(default_factory=list)
    yearly_schedule: list[PeriodEntry] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "final_amount": self.final_amount,
            "total_interest": self.total_interest,
            "truncated": self.truncated,
            "end_date": self.end_date.isoformat(),
            "total_days_requested": self.total_days_requested,
            "daily_schedule": [e.to_dict() for e in self.daily_schedule],
            "monthly_schedule": [e.to_dict() for e in self.monthly_schedule],
            "yearly_schedule": [e.to_dict() for e in self.yearly_schedule],
        }


def _aggregate(daily_schedule: list[DailyEntry], key_fn) -> list[PeriodEntry]:
    buckets: dict = {}
    order: list = []
    for entry in daily_schedule:
        key = key_fn(entry.entry_date)
        if key not in buckets:
            buckets[key] = []
            order.append(key)
        buckets[key].append(entry)

    periods = []
    for key in order:
        bucket = buckets[key]
        periods.append(PeriodEntry(
            period_start=bucket[0].entry_date,
            period_end=bucket[-1].entry_date,
            opening_balance=bucket[0].opening_balance,
            interest_earned=sum(e.interest_earned for e in bucket),
            closing_balance=bucket[-1].closing_balance,
            cumulative_interest=bucket[-1].cumulative_interest,
        ))
    return periods


def calculate(
    principal: float,
    rate_percent: float,
    start_date: date,
    duration_value: int,
    duration_unit: str,
    frequency: str,
    max_integer_digits: int = 20,
) -> CalculationResult:
    """Run the full calculation. Raises ValueError on invalid input —
    callers should validate and translate to a user-facing 400 response
    rather than let this raise into a 500."""
    if principal <= 0:
        raise ValueError("principal must be > 0")
    if rate_percent < 0:
        raise ValueError("rate_percent must be >= 0")
    if duration_value <= 0:
        raise ValueError("duration_value must be > 0")
    if duration_unit not in VALID_DURATION_UNITS:
        raise ValueError(f"duration_unit must be one of {sorted(VALID_DURATION_UNITS)}")
    if frequency not in VALID_FREQUENCIES:
        raise ValueError(f"frequency must be one of {sorted(VALID_FREQUENCIES)}")

    end_date, total_days = _end_date_and_total_days(start_date, duration_value, duration_unit)
    compounding_offsets = _compounding_day_offsets(start_date, total_days, frequency)
    effective_max = min(MAX_RESULT_MAGNITUDE, 10 ** max(4, min(20, max_integer_digits)))

    daily_schedule: list[DailyEntry] = []
    balance = principal
    cumulative_interest = 0.0
    truncated = False

    for day in range(1, total_days + 1):
        opening = balance
        interest = opening * (rate_percent / 100) if day in compounding_offsets else 0.0
        closing = opening + interest
        cumulative_interest += interest
        balance = closing

        daily_schedule.append(DailyEntry(
            day=day,
            entry_date=start_date + timedelta(days=day - 1),
            opening_balance=opening,
            interest_earned=interest,
            closing_balance=closing,
            cumulative_interest=cumulative_interest,
        ))

        if abs(closing) > effective_max:
            truncated = True
            break

    final_amount = daily_schedule[-1].closing_balance if daily_schedule else principal
    total_interest = daily_schedule[-1].cumulative_interest if daily_schedule else 0.0

    return CalculationResult(
        final_amount=final_amount,
        total_interest=total_interest,
        truncated=truncated,
        end_date=end_date,
        total_days_requested=total_days,
        daily_schedule=daily_schedule,
        monthly_schedule=_aggregate(daily_schedule, lambda d: (d.year, d.month)),
        yearly_schedule=_aggregate(daily_schedule, lambda d: d.year),
    )
