from flask import Blueprint, request, jsonify, current_app, Response
from flask_jwt_extended import verify_jwt_in_request, get_jwt_identity
from app.models.signal import Signal, SignalHistory
from app.models.asset import Asset
from app.models.user import User
from app.extensions import db, cache
from app.auth.decorators import login_required, admin_required
from app.services.signals.engine import signal_engine
from app.services.data.fetcher import market_fetcher
from datetime import datetime, timedelta
from sqlalchemy import and_, func
from sqlalchemy.orm import joinedload
import logging
import csv
import io

logger = logging.getLogger(__name__)

signals_bp = Blueprint("signals", __name__)

# ── Persist auto-generate state across restarts (DB-backed singleton row) ─────
_AG_PERSIST_KEYS = (
    "running", "asset_ids", "markets", "timeframes", "signal_filter",
    "min_confidence", "max_per_run", "interval_minutes", "telegram_on_signal",
)

def _ag_save():
    try:
        from app.models.auto_generate_config import AutoGenerateConfig
        row = AutoGenerateConfig.query.first()
        if row is None:
            row = AutoGenerateConfig()
            db.session.add(row)
        for k in _AG_PERSIST_KEYS:
            setattr(row, k, _AG_STATE[k])
        db.session.commit()
    except Exception:
        db.session.rollback()

def _ag_load():
    try:
        from app.models.auto_generate_config import AutoGenerateConfig
        row = AutoGenerateConfig.query.first()
        return row.to_dict() if row else None
    except Exception:
        return None

# ── Server-side Auto Generate state ──────────────────────────────────────────
_AG_STATE = {
    # Watchlist config
    "running":           False,
    "asset_ids":         [],       # list of Asset.id — empty = all active (within selected markets)
    "markets":           [],       # list of market strings — empty = all markets
    "timeframes":        ["1h"],   # list of timeframe strings
    "signal_filter":     "all",
    "min_confidence":    0,
    "max_per_run":       0,
    "interval_minutes":  5,
    "telegram_on_signal": True,    # send Telegram for every new signal
    # Runtime counters (not persisted)
    "runs":                    0,
    "generated":               0,
    "errors":                  0,
    "buy":                     0,
    "sell":                    0,
    "hold":                    0,
    "last_run_at":             None,
    "next_run_at":             None,
    "log":                     [],
    "consecutive_empty_runs":  0,   # silence-failure detection
    "empty_run_alert_sent_at": None,
}
_AG_JOB_ID = "user_auto_generate"


def _ag_log(msg):
    _AG_STATE["log"].append(f"[{datetime.utcnow().strftime('%H:%M:%S')}] {msg}")
    if len(_AG_STATE["log"]) > 100:
        _AG_STATE["log"] = _AG_STATE["log"][-100:]


def _ag_telegram_signal(app, asset_symbol, signal_type, entry, sl, t1, tf, conf):
    """Send Telegram alert for a newly generated signal to all opted-in users."""
    try:
        with app.app_context():
            from app.models.user import User
            from app.tasks.notification_tasks import _send_telegram
            icon = "🟢" if signal_type == "BUY" else "🔴" if signal_type == "SELL" else "🟡"
            text = (
                f"{icon} *{signal_type} Signal: {asset_symbol}*\n"
                f"Entry: `{entry}` | TF: `{tf}` | Conf: `{conf:.0f}%`\n"
                f"SL: `{sl}` | T1: `{t1}`\n"
                f"_Auto-generated by SmartTrade AI_"
            )
            for user in User.query.filter_by(is_active=True, telegram_enabled=True).all():
                if user.telegram_chat_id:
                    _send_telegram(user.telegram_chat_id, text)
    except Exception as e:
        logger.warning(f"Telegram signal alert failed: {e}")


def _run_auto_generate(app):
    with app.app_context():
        sig_filter  = _AG_STATE["signal_filter"]
        min_conf    = _AG_STATE["min_confidence"]
        max_per     = _AG_STATE["max_per_run"]
        timeframes  = _AG_STATE["timeframes"] or ["1h"]
        asset_ids   = _AG_STATE["asset_ids"]  # empty = all active (within markets)
        markets     = _AG_STATE.get("markets") or []  # empty = all markets
        tg_on_sig   = _AG_STATE["telegram_on_signal"]

        # Resolve watchlist assets — asset_ids and markets combine as AND filters
        asset_q = Asset.query.filter_by(is_active=True)
        if markets:
            asset_q = asset_q.filter(Asset.market.in_(markets))
        if asset_ids:
            asset_q = asset_q.filter(Asset.id.in_(asset_ids))
        assets = asset_q.all()

        combos = len(assets) * len(timeframes)
        _AG_STATE["runs"] += 1
        _AG_STATE["last_run_at"] = datetime.utcnow().isoformat()
        interval = _AG_STATE["interval_minutes"]
        _AG_STATE["next_run_at"] = (
            datetime.utcnow() + timedelta(minutes=interval)
        ).isoformat() if interval > 0 else None

        _ag_log(f"▶ Run #{_AG_STATE['runs']} — {len(assets)} assets × {len(timeframes)} TFs ({combos} combos)")
        count = 0

        for timeframe in timeframes:
            for asset in assets:
                if max_per and count >= max_per:
                    break
                try:
                    df = market_fetcher.fetch(asset, timeframe, 220)
                    if df is None:
                        continue

                    result = signal_engine.generate_signal(df, asset, timeframe)
                    if not result:
                        continue

                    stype = result["signal_type"]

                    # Apply signal filter
                    if sig_filter == "buy_sell" and stype not in ("BUY", "SELL"):
                        continue
                    if sig_filter == "buy" and stype != "BUY":
                        continue
                    if sig_filter == "sell" and stype != "SELL":
                        continue
                    if sig_filter == "strong" and result.get("confidence_score", 0) < 70:
                        continue
                    if result.get("confidence_score", 0) < min_conf:
                        continue

                    # Skip if same asset+timeframe already has a recent active signal
                    lockout_min = signal_engine.lockout_minutes(timeframe)
                    cutoff = datetime.utcnow() - timedelta(minutes=lockout_min)
                    recent = Signal.query.filter(and_(
                        Signal.asset_id == asset.id,
                        Signal.timeframe == timeframe,
                        Signal.status == "active",
                        Signal.generated_at >= cutoff,
                    )).first()
                    if recent:
                        age = int((datetime.utcnow() - recent.generated_at).total_seconds() / 60)
                        _ag_log(f"  ↷ {asset.symbol}/{timeframe} skipped — active {age}m ago")
                        continue

                    sig = Signal(
                        asset_id=asset.id,
                        timeframe=timeframe,
                        **{k: v for k, v in result.items()
                           if k in ["signal_type","entry_price","stop_loss","target1","target2","target3",
                                    "risk_reward","confidence_score","confidence_label","trend_score",
                                    "momentum_score","volume_score","pattern_score","ai_score",
                                    "indicators","patterns","reasoning","regime","expires_at"]},
                    )
                    db.session.add(sig)
                    db.session.flush()

                    _AG_STATE["generated"] += 1
                    if stype == "BUY":    _AG_STATE["buy"]  += 1
                    elif stype == "SELL": _AG_STATE["sell"] += 1
                    else:                 _AG_STATE["hold"] += 1
                    count += 1
                    conf = result.get("confidence_score", 0)
                    _ag_log(f"  ✓ {asset.symbol}/{timeframe} → {stype} {conf:.0f}%")

                    # Telegram alert per signal (non-blocking)
                    if tg_on_sig:
                        import threading
                        threading.Thread(
                            target=_ag_telegram_signal,
                            args=[app, asset.symbol, stype,
                                  round(result["entry_price"], 4),
                                  round(result["stop_loss"], 4),
                                  round(result["target1"], 4),
                                  timeframe, conf],
                            daemon=True,
                        ).start()

                except Exception as e:
                    _AG_STATE["errors"] += 1
                    _ag_log(f"  ✗ {asset.symbol}/{timeframe}: {e}")

        try:
            db.session.commit()
            _ag_log(f"✔ Done — {count} signals generated this run")
        except Exception as e:
            db.session.rollback()
            _ag_log(f"✘ Commit error: {e}")

        # ── Silent failure detection ──────────────────────────────────────────
        _EMPTY_RUN_THRESHOLD = 5   # alert after this many consecutive zero-signal runs
        _ALERT_COOLDOWN_HOURS = 2  # don't re-alert within this window
        if count == 0:
            _AG_STATE["consecutive_empty_runs"] = _AG_STATE.get("consecutive_empty_runs", 0) + 1
        else:
            _AG_STATE["consecutive_empty_runs"] = 0
            _AG_STATE["empty_run_alert_sent_at"] = None

        if _AG_STATE["consecutive_empty_runs"] >= _EMPTY_RUN_THRESHOLD:
            last_alert = _AG_STATE.get("empty_run_alert_sent_at")
            now = datetime.utcnow()
            cooldown_ok = (
                last_alert is None or
                (now - datetime.fromisoformat(last_alert)).total_seconds() > _ALERT_COOLDOWN_HOURS * 3600
            )
            if cooldown_ok:
                _AG_STATE["empty_run_alert_sent_at"] = now.isoformat()
                _ag_log(f"⚠️ Alert: {_AG_STATE['consecutive_empty_runs']} consecutive runs with 0 signals")
                import threading
                def _send_failure_alert():
                    try:
                        with app.app_context():
                            from app.models.user import User
                            from app.tasks.notification_tasks import _send_telegram
                            n = _AG_STATE["consecutive_empty_runs"]
                            text = (
                                f"⚠️ *Auto-Generate Alert*\n"
                                f"No signals generated in the last *{n} consecutive runs*.\n"
                                f"This may indicate an API issue, engine error, or over-filtering.\n"
                                f"Check the Auto-Generate log for details."
                            )
                            for user in User.query.filter_by(is_active=True, telegram_enabled=True).all():
                                if user.telegram_chat_id:
                                    _send_telegram(user.telegram_chat_id, text)
                    except Exception as e:
                        logger.warning(f"Empty-run alert failed: {e}")
                threading.Thread(target=_send_failure_alert, daemon=True).start()


def _parse_ag_config(data):
    """Shared parsing for auto-generate config payloads (start/save/run-once)."""
    raw_tfs = data.get("timeframes") or data.get("timeframe", "1h")
    timeframes = raw_tfs if isinstance(raw_tfs, list) else [raw_tfs]

    raw_markets = data.get("markets") or data.get("market") or []
    markets = raw_markets if isinstance(raw_markets, list) else ([raw_markets] if raw_markets else [])
    markets = [m for m in markets if m]  # drop empty strings

    asset_ids = data.get("asset_ids", [])

    return {
        "asset_ids":          [int(x) for x in asset_ids],
        "markets":            markets,
        "timeframes":         timeframes,
        "signal_filter":      data.get("signal_filter", "all"),
        "min_confidence":     float(data.get("min_confidence", 0)),
        "max_per_run":        int(data.get("max_per_run", 0)),
        "interval_minutes":   int(data.get("interval_minutes", 5)),
        "telegram_on_signal": bool(data.get("telegram_on_signal", True)),
    }


@signals_bp.route("/auto-generate/save", methods=["POST"])
@admin_required
def ag_save_config():
    """Persist Auto Generate settings to the DB without starting the scheduler."""
    data = request.get_json() or {}
    _AG_STATE.update(_parse_ag_config(data))
    _ag_save()
    _ag_log("Configuration saved")
    return jsonify({"status": "saved", **_parse_ag_config(data)}), 200


@signals_bp.route("/auto-generate/start", methods=["POST"])
@admin_required
def ag_start():
    from app.extensions import scheduler
    data = request.get_json() or {}

    cfg = _parse_ag_config(data)
    timeframes = cfg["timeframes"]
    asset_ids  = cfg["asset_ids"]
    markets    = cfg["markets"]

    _AG_STATE.update({
        **cfg,
        "running": True,
        "runs": 0, "generated": 0, "errors": 0,
        "buy": 0, "sell": 0, "hold": 0,
        "last_run_at": None, "log": [],
    })

    app = current_app._get_current_object()
    try:
        scheduler.remove_job(_AG_JOB_ID)
    except Exception:
        pass

    interval = _AG_STATE["interval_minutes"]
    if interval > 0:
        scheduler.add_job(
            _run_auto_generate,
            "interval",
            args=[app],
            id=_AG_JOB_ID,
            minutes=interval,
            replace_existing=True,
            next_run_time=datetime.utcnow(),
        )
    else:
        import threading
        threading.Thread(target=_run_auto_generate, args=[app], daemon=True).start()

    _ag_save()
    n_assets = len(asset_ids) if asset_ids else "all"
    mkt_label = "/".join(markets) if markets else "all markets"
    _ag_log(f"Auto Generate started — {n_assets} assets ({mkt_label}) × {timeframes} every {interval}min")
    return jsonify({
        "status": "started", "asset_ids": _AG_STATE["asset_ids"],
        "markets": markets, "timeframes": timeframes,
    }), 200


@signals_bp.route("/auto-generate/stop", methods=["POST"])
@admin_required
def ag_stop():
    from app.extensions import scheduler
    _AG_STATE["running"] = False
    _AG_STATE["next_run_at"] = None
    try:
        scheduler.remove_job(_AG_JOB_ID)
    except Exception:
        pass
    _ag_save()
    _ag_log("⏹ Auto Generate stopped")
    return jsonify({"status": "stopped"}), 200


@signals_bp.route("/auto-generate/status", methods=["GET"])
@login_required
def ag_status():
    return jsonify({
        "running":            _AG_STATE["running"],
        "asset_ids":          _AG_STATE["asset_ids"],
        "markets":            _AG_STATE.get("markets") or [],
        "timeframes":         _AG_STATE["timeframes"],
        "signal_filter":      _AG_STATE["signal_filter"],
        "min_confidence":     _AG_STATE["min_confidence"],
        "interval_minutes":   _AG_STATE["interval_minutes"],
        "telegram_on_signal": _AG_STATE["telegram_on_signal"],
        "runs":               _AG_STATE["runs"],
        "generated":          _AG_STATE["generated"],
        "buy":                _AG_STATE["buy"],
        "sell":               _AG_STATE["sell"],
        "hold":               _AG_STATE["hold"],
        "errors":                  _AG_STATE["errors"],
        "last_run_at":             _AG_STATE["last_run_at"],
        "next_run_at":             _AG_STATE["next_run_at"],
        "consecutive_empty_runs":  _AG_STATE.get("consecutive_empty_runs", 0),
        "log":                     _AG_STATE["log"][-30:],
    }), 200


@signals_bp.route("/auto-generate/watchlist", methods=["GET"])
@login_required
def ag_watchlist():
    """Return all active assets grouped by market — used to build the asset picker."""
    assets = Asset.query.filter_by(is_active=True).order_by(Asset.market, Asset.symbol).all()
    selected = set(_AG_STATE["asset_ids"])
    return jsonify({
        "assets": [
            {**a.to_dict(), "selected": a.id in selected}
            for a in assets
        ],
        "markets": Asset.MARKETS,
        "selected_asset_ids": _AG_STATE["asset_ids"],
        "selected_markets": _AG_STATE.get("markets") or [],
        "selected_timeframes": _AG_STATE["timeframes"],
        "running": _AG_STATE["running"],
    }), 200


@signals_bp.route("/auto-generate/run-once", methods=["POST"])
@admin_required
def ag_run_once():
    data = request.get_json() or {}
    raw_tfs = data.get("timeframes") or data.get("timeframe")
    if raw_tfs:
        _AG_STATE["timeframes"] = raw_tfs if isinstance(raw_tfs, list) else [raw_tfs]
    if "asset_ids" in data:
        _AG_STATE["asset_ids"] = [int(x) for x in data["asset_ids"]]
    if "markets" in data or "market" in data:
        raw_markets = data.get("markets") or data.get("market") or []
        _AG_STATE["markets"] = raw_markets if isinstance(raw_markets, list) else ([raw_markets] if raw_markets else [])
    if "signal_filter" in data:
        _AG_STATE["signal_filter"] = data["signal_filter"]
    if "min_confidence" in data:
        _AG_STATE["min_confidence"] = float(data["min_confidence"])
    if "max_per_run" in data:
        _AG_STATE["max_per_run"] = int(data["max_per_run"])
    app = current_app._get_current_object()
    import threading
    threading.Thread(target=_run_auto_generate, args=[app], daemon=True).start()
    return jsonify({"status": "running"}), 200


@signals_bp.route("/mtf-matrix", methods=["GET"])
@login_required
def mtf_matrix():
    """
    Computes live indicator-based ratings per (asset, timeframe).
    Never returns — because ratings are derived from live OHLCV data, not DB signals.
    """
    from app.services.data.fetcher import market_fetcher
    from app.services.indicators.calculator import calculate_all_indicators
    from concurrent.futures import ThreadPoolExecutor
    from app.auth.decorators import get_current_user
    from app.models.user import UserAssetPreference

    user       = get_current_user()
    market     = request.args.get("market") or "all"

    # ── Serve from pre-warmed global cache ───────────────────────
    global_mtf = cache.get("mtf_matrix_all")
    if global_mtf:
        prefs = {p.asset_id: p.enabled
                 for p in UserAssetPreference.query.filter_by(user_id=user.id).all()}
        assets = global_mtf["assets"]
        matrix = global_mtf["matrix"]
        if market != "all":
            assets = [a for a in assets if a.get("market") == market]
            matrix = {k: v for k, v in matrix.items()
                      if any(a["id"] == k for a in assets)}
        if prefs:
            assets = [a for a in assets if prefs.get(a["id"], True)]
            matrix = {k: v for k, v in matrix.items()
                      if any(a["id"] == k for a in assets)}
        return jsonify({"matrix": matrix, "assets": assets,
                        "timeframes": global_mtf["timeframes"]}), 200

    # ── Cold path ─────────────────────────────────────────────────
    prefs = {p.asset_id: p.enabled for p in UserAssetPreference.query.filter_by(user_id=user.id).all()}
    timeframes = ["5m", "15m", "30m", "1h", "2h", "4h", "1d"]
    asset_q = Asset.query.filter_by(is_active=True)
    if market != "all":
        asset_q = asset_q.filter_by(market=market)
    all_assets = asset_q.order_by(Asset.market, Asset.symbol).all()
    assets = [a for a in all_assets if prefs.get(a.id, True)] if prefs else all_assets

    all_data = market_fetcher.fetch_many(assets, timeframes, limit=200)

    def _rate_asset(a):
        dfs = all_data.get(a.symbol, {})
        row = {}
        for tf in timeframes:
            try:
                df = dfs.get(tf)
                if df is None or len(df) < 52:
                    row[tf] = None; continue
                ind   = calculate_all_indicators(df)
                close = float(df["close"].iloc[-1])
                row[tf] = _mtf_rating(ind, close)
            except Exception:
                row[tf] = None
        return a.id, row

    matrix = {}
    with ThreadPoolExecutor(max_workers=min(8, len(assets))) as ex:
        for asset_id, row in ex.map(_rate_asset, assets):
            matrix[asset_id] = row

    payload = {
        "matrix": matrix,
        "assets": [{"id": a.id, "symbol": a.symbol, "name": a.name, "market": a.market} for a in assets],
        "timeframes": timeframes,
    }
    cache.set("mtf_matrix_all", payload, timeout=150)
    return jsonify(payload), 200


def _mtf_rating(ind, close):
    """Score 12 indicators → BUY / SELL / HOLD signal with confidence %."""
    buy = sell = neutral = 0

    def vote(v):
        nonlocal buy, sell, neutral
        if v == "buy":     buy    += 1
        elif v == "sell":  sell   += 1
        else:              neutral += 1

    rsi = ind.get("rsi")
    if rsi is not None:
        vote("buy" if rsi < 30 else "sell" if rsi > 70 else "neutral")

    macd, macd_sig = ind.get("macd"), ind.get("macd_signal")
    if macd is not None and macd_sig is not None:
        vote("buy" if macd > macd_sig else "sell" if macd < macd_sig else "neutral")

    cci = ind.get("cci")
    if cci is not None:
        vote("buy" if cci < -100 else "sell" if cci > 100 else "neutral")

    roc = ind.get("roc")
    if roc is not None:
        vote("buy" if roc > 0 else "sell" if roc < 0 else "neutral")

    stoch_k = ind.get("stoch_rsi_k")
    if stoch_k is not None:
        vote("buy" if stoch_k < 20 else "sell" if stoch_k > 80 else "neutral")

    for ma_key in ["ema20", "ema50", "ema100", "ema200", "sma20", "sma50"]:
        ma = ind.get(ma_key)
        if ma:
            vote("buy" if close > ma else "sell")

    tenkan, kijun = ind.get("ichimoku_tenkan"), ind.get("ichimoku_kijun")
    if tenkan and kijun:
        vote("buy" if tenkan > kijun else "sell")

    bb_upper, bb_lower = ind.get("bb_upper"), ind.get("bb_lower")
    if bb_upper and bb_lower:
        vote("buy" if close < bb_lower else "sell" if close > bb_upper else "neutral")

    st_dir = ind.get("supertrend_direction")
    if st_dir:
        vote("buy" if st_dir == "up" else "sell")

    cmf = ind.get("cmf")
    if cmf is not None:
        vote("buy" if cmf > 0 else "sell" if cmf < 0 else "neutral")

    total = buy + sell + neutral
    if not total:
        return None

    score = (buy - sell) / total   # -1 … +1
    confidence = round(max(buy, sell) / total * 100)

    if score >= 0.5:    signal = "BUY"
    elif score <= -0.5: signal = "SELL"
    else:               signal = "HOLD"

    return {
        "signal_type": signal,
        "confidence":  confidence,
        "buy":         buy,
        "sell":        sell,
        "neutral":     neutral,
        "score":       round(score, 2),
    }


@signals_bp.route("/confluence/<int:asset_id>", methods=["GET"])
@login_required
def get_confluence(asset_id):
    """
    Compute per-timeframe confluence for an asset.
    Returns how many TFs align BUY vs SELL vs neutral.
    """
    from app.services.data.fetcher import market_fetcher
    from app.services.indicators.calculator import calculate_all_indicators

    asset = Asset.query.get_or_404(asset_id)

    ck = f"confluence_{asset_id}"
    cached = cache.get(ck)
    if cached:
        return jsonify(cached), 200

    timeframes = ["5m", "15m", "30m", "1h", "2h", "4h", "1d"]
    all_data = market_fetcher.fetch_many([asset], timeframes, limit=100)
    dfs = all_data.get(asset.symbol, {})

    # Get primary signal direction from the most recent DB signal
    primary_signal = Signal.query.filter(
        Signal.asset_id == asset_id,
        Signal.status == "active",
        Signal.signal_type.in_(["BUY", "SELL"]),
    ).order_by(Signal.generated_at.desc()).first()
    primary_direction = primary_signal.signal_type if primary_signal else None

    buy_tfs = sell_tfs = neutral_tfs = 0
    tf_details = {}

    for tf in timeframes:
        try:
            df = dfs.get(tf)
            if df is None or len(df) < 52:
                neutral_tfs += 1
                tf_details[tf] = None
                continue
            ind = calculate_all_indicators(df)
            close = float(df["close"].iloc[-1])
            rating = _mtf_rating(ind, close)
            if rating is None:
                neutral_tfs += 1
                tf_details[tf] = None
                continue
            sig = rating["signal_type"]
            tf_details[tf] = sig
            if sig == "BUY":
                buy_tfs += 1
            elif sig == "SELL":
                sell_tfs += 1
            else:
                neutral_tfs += 1
        except Exception:
            neutral_tfs += 1
            tf_details[tf] = None

    total = len(timeframes)
    dominant = "BUY" if buy_tfs >= sell_tfs else "SELL"
    dominant_count = max(buy_tfs, sell_tfs)
    confluence_str = f"{dominant_count}/{total} {dominant}"

    payload = {
        "asset_id": asset_id,
        "symbol": asset.symbol,
        "buy_tfs": buy_tfs,
        "sell_tfs": sell_tfs,
        "neutral_tfs": neutral_tfs,
        "total": total,
        "confluence": confluence_str,
        "primary_direction": primary_direction,
        "tf_details": tf_details,
    }
    cache.set(ck, payload, timeout=120)
    return jsonify(payload), 200


@signals_bp.route("/open-pnl", methods=["GET"])
@login_required
def open_pnl():
    """Return unrealized P&L for all active signals with live prices."""
    user_id = get_jwt_identity()
    cache_key = f"open_pnl_{user_id}"
    cached = cache.get(cache_key)
    if cached:
        return jsonify(cached), 200

    active_signals = Signal.query.filter_by(status="active") \
        .order_by(Signal.generated_at.desc()).all()

    asset_ids  = {s.asset_id for s in active_signals}
    assets_map = {a.id: a for a in Asset.query.filter(Asset.id.in_(asset_ids)).all()}

    now = datetime.utcnow()
    result = []
    for s in active_signals:
        asset = assets_map.get(s.asset_id)
        if not asset:
            continue

        current_price = None
        try:
            ticker = market_fetcher.fetch_ticker(asset)
            if ticker:
                current_price = float(
                    ticker.get("last_price") or ticker.get("price") or ticker.get("close") or 0
                ) or None
        except Exception:
            pass

        entry = float(s.entry_price or 0)
        pnl_pct = None
        if current_price and entry:
            if s.signal_type == "BUY":
                pnl_pct = (current_price - entry) / entry * 100
            elif s.signal_type == "SELL":
                pnl_pct = (entry - current_price) / entry * 100

        sl   = float(s.stop_loss or 0) or None
        tgt1 = float(s.target1   or 0) or None
        dist_sl  = None
        dist_t1  = None
        if current_price and sl and entry:
            dist_sl  = abs(current_price - sl)  / entry * 100
        if current_price and tgt1 and entry:
            dist_t1  = abs(tgt1 - current_price) / entry * 100

        age_hours = round((now - s.generated_at).total_seconds() / 3600, 1) if s.generated_at else None

        result.append({
            "signal_id":          s.id,
            "asset":              asset.symbol,
            "asset_id":           asset.id,
            "symbol":             asset.symbol,
            "timeframe":          s.timeframe,
            "signal_type":        s.signal_type,
            "entry_price":        entry,
            "current_price":      current_price,
            "pnl_pct":            round(pnl_pct, 2) if pnl_pct is not None else None,
            "stop_loss":          sl,
            "target1":            tgt1,
            "distance_to_sl_pct": round(dist_sl,  2) if dist_sl  is not None else None,
            "distance_to_t1_pct": round(dist_t1,  2) if dist_t1  is not None else None,
            "status":             s.status,
            "age_hours":          age_hours,
        })

    cache.set(cache_key, result, timeout=30)
    return jsonify(result), 200


@signals_bp.route("/", methods=["GET"])
@login_required
def get_signals():
    market = request.args.get("market")
    asset_id = request.args.get("asset_id", type=int)
    timeframe = request.args.get("timeframe")
    signal_type = request.args.get("signal_type")
    min_confidence = float(request.args.get("min_confidence", 0))
    page = int(request.args.get("page", 1))
    per_page = int(request.args.get("per_page", 20))

    user_id = get_jwt_identity()
    user = User.query.get(user_id)

    query = Signal.query.options(joinedload(Signal.asset)).join(Asset)
    if asset_id:
        query = query.filter(Signal.asset_id == asset_id)
    if market:
        query = query.filter(Asset.market == market)
    if timeframe:
        query = query.filter(Signal.timeframe == timeframe)
    if signal_type:
        query = query.filter(Signal.signal_type == signal_type)
    if min_confidence:
        query = query.filter(Signal.confidence_score >= min_confidence)

    # Free users get delayed signals
    if user and user.subscription and user.subscription.signal_delay_minutes > 0:
        delay = user.subscription.signal_delay_minutes
        cutoff = datetime.utcnow() - timedelta(minutes=delay)
        query = query.filter(Signal.generated_at <= cutoff)

    signals = query.filter(Signal.status == "active") \
        .order_by(Signal.generated_at.desc()) \
        .paginate(page=page, per_page=per_page, error_out=False)

    return jsonify({
        "signals": [s.to_dict() for s in signals.items],
        "total": signals.total,
        "page": page,
        "pages": signals.pages,
    }), 200


@signals_bp.route("/<int:signal_id>", methods=["GET"])
@login_required
def get_signal(signal_id):
    signal = Signal.query.get_or_404(signal_id)
    return jsonify(signal.to_dict()), 200


@signals_bp.route("/generate", methods=["POST"])
@login_required
def generate_signal():
    data = request.get_json()
    symbol = data.get("symbol")
    timeframe = data.get("timeframe", "1h")

    asset = Asset.query.filter_by(symbol=symbol, is_active=True).first()
    if not asset:
        return jsonify({"error": "Asset not found"}), 404

    df = market_fetcher.fetch(asset, timeframe)
    if df is None:
        return jsonify({"error": "Failed to fetch market data"}), 503

    result = signal_engine.generate_signal(df, asset, timeframe, force=True)
    if not result:
        return jsonify({"error": "Could not generate signal — market conditions not met (low volatility or no clear direction)"}), 422

    # AI boost
    try:
        from app.services.ai.predictor import ai_predictor
        prediction = ai_predictor.predict(df, asset.symbol, timeframe)
        result["ai_score"] = prediction.get("confidence", 50) * 0.2
        result["confidence_score"] = min(100, result["confidence_score"] + result["ai_score"] * 0.1)
    except Exception:
        pass

    signal = Signal(
        asset_id=asset.id,
        timeframe=timeframe,
        **{k: v for k, v in result.items()
           if k in ["signal_type", "entry_price", "stop_loss", "target1", "target2", "target3",
                    "risk_reward", "confidence_score", "confidence_label", "trend_score",
                    "momentum_score", "volume_score", "pattern_score", "ai_score",
                    "indicators", "patterns", "reasoning", "regime", "expires_at"]},
    )
    signal.set_confidence_label()
    db.session.add(signal)
    db.session.commit()

    return jsonify(signal.to_dict()), 201


@signals_bp.route("/performance/by-asset", methods=["GET"])
@login_required
def signal_performance():
    """Signal outcome analytics from closed signal history, broken down by
    asset x timeframe with a configurable lookback window.

    NOTE: this used to be registered at the same URL as get_performance()
    below (both were "/performance") — Flask only ever routes to the
    later-registered view function for a given rule, so this one was
    completely unreachable dead code. Moved to its own path; the
    calibration data it computed is now merged into get_performance()
    (see _confidence_calibration_bands) since that's what the dashboard
    actually calls.

    Query params: ?days=<lookback, default 90> &market=<optional filter>
    """
    try:
        days = int(request.args.get("days", 90))
    except (TypeError, ValueError):
        days = 90
    market = request.args.get("market")

    cutoff = datetime.utcnow() - timedelta(days=days)
    q = SignalHistory.query.filter(SignalHistory.closed_at >= cutoff)
    rows = q.all()

    # Asset map (for symbol/market labels + optional market filter)
    asset_ids = {r.asset_id for r in rows if r.asset_id}
    assets_map = {a.id: a for a in Asset.query.filter(Asset.id.in_(asset_ids)).all()} if asset_ids else {}
    if market:
        rows = [r for r in rows if (a := assets_map.get(r.asset_id)) and a.market == market]

    def _stats(items):
        total = len(items)
        wins = [r for r in items if r.outcome == "win"]
        losses = [r for r in items if r.outcome == "loss"]
        gross_win = sum((r.pnl_pct or 0) for r in wins)
        gross_loss = abs(sum((r.pnl_pct or 0) for r in losses))
        return {
            "total": total,
            "wins": len(wins),
            "losses": len(losses),
            "win_rate": round(len(wins) / total * 100, 1) if total else 0,
            "avg_pnl_pct": round(sum((r.pnl_pct or 0) for r in items) / total, 3) if total else 0,
            "profit_factor": round(gross_win / gross_loss, 2) if gross_loss > 0
                             else (None if gross_win > 0 else 0),   # None = no losing trades
        }

    # ── Overall ──
    overall = _stats(rows)

    # ── Per asset × timeframe ──
    from collections import defaultdict
    buckets: dict[tuple, list] = defaultdict(list)
    for r in rows:
        buckets[(r.asset_id, r.timeframe)].append(r)
    by_asset_tf = []
    for (aid, tf), items in buckets.items():
        a = assets_map.get(aid)
        s = _stats(items)
        s.update({"asset": a.symbol if a else str(aid),
                  "market": a.market if a else None, "timeframe": tf})
        by_asset_tf.append(s)
    by_asset_tf.sort(key=lambda x: (-x["total"], -x["win_rate"]))

    # ── Confidence calibration: does an 80%-confidence signal win ~80%? ──
    conf_bands = [(0, 60, "Weak"), (60, 75, "Moderate"), (75, 90, "Strong"), (90, 101, "Very Strong")]
    calibration = []
    for lo, hi, label in conf_bands:
        band = [r for r in rows if lo <= (r.confidence_score or 0) < hi]
        decisive = [r for r in band if r.outcome in ("win", "loss")]
        actual_win = round(sum(1 for r in decisive if r.outcome == "win") / len(decisive) * 100, 1) \
                     if decisive else None
        calibration.append({
            "band": label, "range": f"{lo}-{hi - 1}",
            "signals": len(band),
            "actual_win_rate": actual_win,   # compare against the band midpoint
            "expected_win_rate": (lo + hi) // 2,
        })

    return jsonify({
        "lookback_days": days,
        "overall": overall,
        "by_asset_timeframe": by_asset_tf[:50],
        "calibration": calibration,
    }), 200


@signals_bp.route("/summary", methods=["GET"])
@login_required
@cache.cached(timeout=60, key_prefix="signals_summary")
def get_summary():
    from sqlalchemy import func
    today = datetime.utcnow().replace(hour=0, minute=0, second=0, microsecond=0)

    counts = db.session.query(
        Signal.signal_type, func.count(Signal.id)
    ).filter(Signal.generated_at >= today).group_by(Signal.signal_type).all()

    summary = {t: c for t, c in counts}

    history = SignalHistory.query
    total_h = history.count()
    wins    = history.filter(SignalHistory.outcome == "win").count()
    win_rate = round((wins / total_h * 100), 1) if total_h else 0

    # Average confidence today
    avg_conf_row = db.session.query(func.avg(Signal.confidence_score)).filter(
        Signal.generated_at >= today).scalar()
    avg_confidence = round(float(avg_conf_row), 1) if avg_conf_row else 0

    # Top signal today (highest confidence, BUY or SELL only)
    top_signal_obj = Signal.query.join(Asset, Signal.asset_id == Asset.id).filter(
        Signal.generated_at >= today,
        Signal.signal_type.in_(["BUY", "SELL"])
    ).order_by(Signal.confidence_score.desc()).first()

    top_signal = None
    if top_signal_obj:
        # asset already joined above — access via relationship (joinedload not needed for single row)
        a = top_signal_obj.asset
        top_signal = {
            "asset":            a.symbol if a else "?",
            "market":           a.market if a else "",
            "timeframe":        top_signal_obj.timeframe,
            "signal_type":      top_signal_obj.signal_type,
            "confidence_score": top_signal_obj.confidence_score,
        }

    # Open alerts (active signals)
    open_alerts = Signal.query.filter_by(status="active").count()

    return jsonify({
        "buy_today":       summary.get("BUY",  0),
        "sell_today":      summary.get("SELL", 0),
        "hold_today":      summary.get("HOLD", 0),
        "exit_today":      summary.get("EXIT", 0),
        "win_rate":        win_rate,
        "total_historical": total_h,
        "avg_confidence":  avg_confidence,
        "open_alerts":     open_alerts,
        "top_signal":      top_signal,
    }), 200


@signals_bp.route("/history", methods=["GET"])
@login_required
def signal_history():
    page = int(request.args.get("page", 1))
    per_page = int(request.args.get("per_page", 20))
    market = request.args.get("market")

    outcome = request.args.get("outcome")
    query = SignalHistory.query.options(joinedload(SignalHistory.asset)).join(Asset, SignalHistory.asset_id == Asset.id)
    if market:
        query = query.filter(Asset.market == market)
    if outcome:
        query = query.filter(SignalHistory.outcome == outcome)

    history = query.order_by(SignalHistory.closed_at.desc()) \
        .paginate(page=page, per_page=per_page, error_out=False)

    items = []
    for h in history.items:
        a = h.asset
        items.append({
            "id":          h.id,
            "asset":       a.symbol if a else "?",
            "timeframe":   h.timeframe,
            "signal_type": h.signal_type,
            "entry":       h.entry_price,
            "exit":        h.exit_price,
            "pnl_pct":     h.pnl_pct,
            "outcome":     h.outcome,
            "confidence":  h.confidence_score,
            "closed_at":   h.closed_at.isoformat() if h.closed_at else None,
        })

    return jsonify({
        "history": items,
        "total": history.total,
        "pages": history.pages,
    }), 200


@signals_bp.route("/analytics", methods=["GET"])
@login_required
def get_analytics():
    """Return signal performance analytics from Signal + SignalHistory tables."""

    # ── Overall stats ────────────────────────────────────────────────────────
    total_signals = Signal.query.count()
    active_count  = Signal.query.filter_by(status="active").count()
    closed_count  = Signal.query.filter(Signal.status != "active").count()

    hist_q    = SignalHistory.query
    total_h   = hist_q.count()
    wins      = hist_q.filter(SignalHistory.outcome == "win").count()
    losses    = hist_q.filter(SignalHistory.outcome == "loss").count()
    win_rate  = round(wins / total_h * 100, 1) if total_h else 0.0

    avg_rr_row = db.session.query(func.avg(Signal.risk_reward)).scalar()
    avg_rr     = round(float(avg_rr_row), 2) if avg_rr_row else 0.0

    # ── By market ────────────────────────────────────────────────────────────
    mkt_rows = (
        db.session.query(Asset.market, func.count(SignalHistory.id).label("total"))
        .join(SignalHistory, SignalHistory.asset_id == Asset.id)
        .group_by(Asset.market)
        .all()
    )
    by_market = []
    for mkt, total in mkt_rows:
        w = SignalHistory.query.join(Asset, SignalHistory.asset_id == Asset.id).filter(
            Asset.market == mkt, SignalHistory.outcome == "win").count()
        l = SignalHistory.query.join(Asset, SignalHistory.asset_id == Asset.id).filter(
            Asset.market == mkt, SignalHistory.outcome == "loss").count()
        by_market.append({
            "market": mkt, "total": total, "wins": w, "losses": l,
            "win_rate": round(w / total * 100, 1) if total else 0.0,
        })

    # ── By timeframe ─────────────────────────────────────────────────────────
    tf_rows = (
        db.session.query(SignalHistory.timeframe, func.count(SignalHistory.id).label("total"))
        .group_by(SignalHistory.timeframe)
        .all()
    )
    by_timeframe = []
    for tf, total in tf_rows:
        w = SignalHistory.query.filter_by(timeframe=tf, outcome="win").count()
        by_timeframe.append({
            "timeframe": tf, "total": total, "wins": w,
            "win_rate": round(w / total * 100, 1) if total else 0.0,
        })

    # ── By signal type ───────────────────────────────────────────────────────
    st_rows = (
        db.session.query(SignalHistory.signal_type, func.count(SignalHistory.id).label("total"))
        .group_by(SignalHistory.signal_type)
        .all()
    )
    by_signal_type = []
    for st, total in st_rows:
        w = SignalHistory.query.filter_by(signal_type=st, outcome="win").count()
        by_signal_type.append({
            "signal_type": st, "total": total, "wins": w,
            "win_rate": round(w / total * 100, 1) if total else 0.0,
        })

    # ── Confidence buckets ───────────────────────────────────────────────────
    confidence_buckets = []
    for lo, hi, label in [(50,60,"50-60%"),(60,70,"60-70%"),(70,80,"70-80%"),(80,90,"80-90%"),(90,101,"90-100%")]:
        rows = SignalHistory.query.filter(
            SignalHistory.confidence_score >= lo,
            SignalHistory.confidence_score < hi,
        )
        total = rows.count()
        w     = rows.filter(SignalHistory.outcome == "win").count()
        confidence_buckets.append({
            "range": label, "total": total,
            "win_rate": round(w / total * 100, 1) if total else 0.0,
        })

    # ── Recent performance (last 30 days) ────────────────────────────────────
    cutoff = datetime.utcnow() - timedelta(days=30)
    recent_rows = (
        db.session.query(
            func.date(SignalHistory.closed_at).label("day"),
            func.count(SignalHistory.id).label("total"),
        )
        .filter(SignalHistory.closed_at >= cutoff)
        .group_by(func.date(SignalHistory.closed_at))
        .order_by(func.date(SignalHistory.closed_at))
        .all()
    )
    recent_performance = []
    for row in recent_rows:
        day_str = str(row.day)
        w = SignalHistory.query.filter(
            func.date(SignalHistory.closed_at) == row.day,
            SignalHistory.outcome == "win",
        ).count()
        l = SignalHistory.query.filter(
            func.date(SignalHistory.closed_at) == row.day,
            SignalHistory.outcome == "loss",
        ).count()
        recent_performance.append({"date": day_str, "signals": row.total, "wins": w, "losses": l})

    # ── Top assets (min 5 trades) ─────────────────────────────────────────────
    asset_rows = (
        db.session.query(Asset.symbol, Asset.market, func.count(SignalHistory.id).label("total"))
        .join(SignalHistory, SignalHistory.asset_id == Asset.id)
        .group_by(Asset.id, Asset.symbol, Asset.market)
        .having(func.count(SignalHistory.id) >= 5)
        .order_by(func.count(SignalHistory.id).desc())
        .limit(20)
        .all()
    )
    top_assets = []
    for sym, mkt, total in asset_rows:
        w = (
            SignalHistory.query
            .join(Asset, SignalHistory.asset_id == Asset.id)
            .filter(Asset.symbol == sym, SignalHistory.outcome == "win")
            .count()
        )
        top_assets.append({
            "symbol": sym, "market": mkt, "total": total, "wins": w,
            "win_rate": round(w / total * 100, 1) if total else 0.0,
        })
    top_assets.sort(key=lambda x: x["win_rate"], reverse=True)

    return jsonify({
        "overall": {
            "total_signals": total_signals,
            "active": active_count,
            "closed": closed_count,
            "win_rate": win_rate,
            "avg_rr_achieved": avg_rr,
            "total_wins": wins,
            "total_losses": losses,
        },
        "by_market": by_market,
        "by_timeframe": by_timeframe,
        "by_signal_type": by_signal_type,
        "confidence_buckets": confidence_buckets,
        "recent_performance": recent_performance,
        "top_assets": top_assets,
    }), 200



@signals_bp.route("/performance", methods=["GET"])
@login_required
def get_performance():
    """Personal performance dashboard — aggregated stats from SignalHistory."""

    hist_q = SignalHistory.query
    total_closed = hist_q.count()
    wins   = hist_q.filter(SignalHistory.outcome == "win").count()
    win_rate = round(wins / total_closed * 100, 1) if total_closed else 0.0

    avg_rr_row = db.session.query(
        func.avg(Signal.risk_reward)
    ).join(SignalHistory, SignalHistory.signal_id == Signal.id).scalar()
    avg_rr = round(float(avg_rr_row), 2) if avg_rr_row else 0.0

    total_pnl_row = db.session.query(func.sum(SignalHistory.pnl_pct)).scalar()
    total_pnl = round(float(total_pnl_row), 2) if total_pnl_row else 0.0

    avg_dur_row = db.session.query(func.avg(SignalHistory.duration_minutes)).scalar()
    avg_duration = int(avg_dur_row) if avg_dur_row else 0

    best_row  = db.session.query(func.max(SignalHistory.pnl_pct)).scalar()
    worst_row = db.session.query(func.min(SignalHistory.pnl_pct)).scalar()
    best_win   = round(float(best_row),  2) if best_row  is not None else 0.0
    worst_loss = round(float(worst_row), 2) if worst_row is not None else 0.0

    # ── By market ─────────────────────────────────────────────────────────────
    mkt_rows = (
        db.session.query(Asset.market, func.count(SignalHistory.id).label("trades"))
        .join(SignalHistory, SignalHistory.asset_id == Asset.id)
        .group_by(Asset.market).all()
    )
    by_market = []
    for mkt, trades in mkt_rows:
        w = (SignalHistory.query
             .join(Asset, SignalHistory.asset_id == Asset.id)
             .filter(Asset.market == mkt, SignalHistory.outcome == "win").count())
        avg_pnl_r = (db.session.query(func.avg(SignalHistory.pnl_pct))
                     .join(Asset, SignalHistory.asset_id == Asset.id)
                     .filter(Asset.market == mkt).scalar())
        by_market.append({
            "market": mkt, "trades": trades,
            "win_rate": round(w / trades * 100, 1) if trades else 0.0,
            "avg_pnl": round(float(avg_pnl_r), 2) if avg_pnl_r else 0.0,
        })

    # ── By timeframe ─────────────────────────────────────────────────────────
    tf_rows = (
        db.session.query(SignalHistory.timeframe, func.count(SignalHistory.id).label("trades"))
        .group_by(SignalHistory.timeframe).all()
    )
    by_timeframe = []
    for tf, trades in tf_rows:
        w = SignalHistory.query.filter_by(timeframe=tf, outcome="win").count()
        avg_pnl_r = (db.session.query(func.avg(SignalHistory.pnl_pct))
                     .filter(SignalHistory.timeframe == tf).scalar())
        by_timeframe.append({
            "timeframe": tf, "trades": trades,
            "win_rate": round(w / trades * 100, 1) if trades else 0.0,
            "avg_pnl": round(float(avg_pnl_r), 2) if avg_pnl_r else 0.0,
        })

    # ── By signal type ────────────────────────────────────────────────────────
    st_rows = (
        db.session.query(SignalHistory.signal_type, func.count(SignalHistory.id).label("trades"))
        .group_by(SignalHistory.signal_type).all()
    )
    by_signal_type = []
    for st, trades in st_rows:
        w = SignalHistory.query.filter_by(signal_type=st, outcome="win").count()
        by_signal_type.append({
            "type": st, "trades": trades,
            "win_rate": round(w / trades * 100, 1) if trades else 0.0,
        })

    # ── By confidence bucket ──────────────────────────────────────────────────
    by_confidence = []
    for lo, hi, label in [(50,60,"50-60%"),(60,70,"60-70%"),(70,80,"70-80%"),(80,90,"80-90%"),(90,101,"90-100%")]:
        brows  = SignalHistory.query.filter(
            SignalHistory.confidence_score >= lo, SignalHistory.confidence_score < hi)
        trades = brows.count()
        w      = brows.filter(SignalHistory.outcome == "win").count()
        avg_pnl_r = (db.session.query(func.avg(SignalHistory.pnl_pct))
                     .filter(SignalHistory.confidence_score >= lo, SignalHistory.confidence_score < hi).scalar())
        by_confidence.append({
            "bucket": label, "trades": trades,
            "win_rate": round(w / trades * 100, 1) if trades else 0.0,
            "avg_pnl": round(float(avg_pnl_r), 2) if avg_pnl_r else 0.0,
        })

    # ── Daily P&L last 30 days ────────────────────────────────────────────────
    cutoff = datetime.utcnow() - timedelta(days=30)
    day_rows = (
        db.session.query(
            func.date(SignalHistory.closed_at).label("day"),
            func.count(SignalHistory.id).label("trades"),
            func.sum(SignalHistory.pnl_pct).label("pnl"),
        )
        .filter(SignalHistory.closed_at >= cutoff)
        .group_by(func.date(SignalHistory.closed_at))
        .order_by(func.date(SignalHistory.closed_at))
        .all()
    )
    daily_pnl = []
    for row in day_rows:
        day_str = str(row.day)
        w = SignalHistory.query.filter(
            func.date(SignalHistory.closed_at) == row.day,
            SignalHistory.outcome == "win").count()
        daily_pnl.append({
            "date": day_str,
            "pnl_pct": round(float(row.pnl), 2) if row.pnl else 0.0,
            "trades": row.trades,
            "wins": w,
        })

    # ── Hourly win rate (UTC+5:30 = +330 min) ────────────────────────────────
    IST_OFFSET = 330
    try:
        hourly_rows = (
            db.session.query(
                func.strftime('%H', func.datetime(
                    SignalHistory.closed_at, f'+{IST_OFFSET} minutes'
                )).label("hour"),
                func.count(SignalHistory.id).label("trades"),
            )
            .group_by("hour")
            .all()
        )
        hourly_win_rate = []
        for row in hourly_rows:
            h = int(row.hour)
            w = SignalHistory.query.filter(
                func.strftime('%H', func.datetime(
                    SignalHistory.closed_at, f'+{IST_OFFSET} minutes'
                )) == str(h).zfill(2),
                SignalHistory.outcome == "win"
            ).count()
            hourly_win_rate.append({"hour": h, "win_rate": round(w / row.trades * 100, 1) if row.trades else 0.0, "trades": row.trades})
        hourly_win_rate.sort(key=lambda x: x["hour"])
    except Exception:
        hourly_win_rate = []

    # ── Confidence calibration: does an 80%-confidence signal actually win ~80%? ──
    # This used to live in a second, separately-registered `/performance`
    # route (`signal_performance`, now `_confidence_calibration_bands` below)
    # that Flask silently never routed to — both functions were bound to the
    # exact same URL rule, so only the later-registered one (this one) was
    # ever reachable, and the dashboard's Confidence Calibration chart
    # (dashboard.js `perf?.calibration`) always rendered empty.
    calibration = _confidence_calibration_bands()

    return jsonify({
        "overall": {
            "total_closed": total_closed,
            "win_rate": win_rate,
            "avg_rr": avg_rr,
            "total_pnl_pct": total_pnl,
            "avg_duration_minutes": avg_duration,
            "best_win_pct": best_win,
            "worst_loss_pct": worst_loss,
        },
        "by_market": by_market,
        "by_timeframe": by_timeframe,
        "by_signal_type": by_signal_type,
        "by_confidence": by_confidence,
        "calibration": calibration,
        "daily_pnl": daily_pnl,
        "hourly_win_rate": hourly_win_rate,
    }), 200


def _confidence_calibration_bands():
    """Do higher-confidence signals actually win more? Buckets closed
    signals by confidence band and compares actual win rate to the band's
    expected midpoint — the key measure of whether the confidence score is
    trustworthy. Extracted from the old signal_performance() so it can feed
    both /performance and any future dedicated endpoint."""
    rows = SignalHistory.query.all()
    conf_bands = [(0, 60, "Weak"), (60, 75, "Moderate"), (75, 90, "Strong"), (90, 101, "Very Strong")]
    calibration = []
    for lo, hi, label in conf_bands:
        band = [r for r in rows if lo <= (r.confidence_score or 0) < hi]
        decisive = [r for r in band if r.outcome in ("win", "loss")]
        actual_win = round(sum(1 for r in decisive if r.outcome == "win") / len(decisive) * 100, 1) \
                     if decisive else None
        calibration.append({
            "band": label, "range": f"{lo}-{hi - 1}",
            "signals": len(band),
            "actual_win_rate": actual_win,
            "expected_win_rate": (lo + hi) // 2,
        })
    return calibration


# ─── Backtest & Proof-of-Performance ──────────────────────────────────────────

@signals_bp.route("/history-stats", methods=["GET"])
@login_required
def history_stats():
    """
    Proven performance from real closed signals (SignalHistory), with both the
    dashboard-style raw win rate and the true win rate (excluding undecided
    trades). Includes a 'what-if' expiry diagnostic.
    """
    from app.services.backtest import analyze_history, whatif_expiry
    return jsonify({
        "stats": analyze_history(),
        "whatif_expiry": whatif_expiry(),
    }), 200


@signals_bp.route("/backtest", methods=["GET"])
@login_required
def backtest():
    """
    Walk-forward backtest that replays historical candles through the live
    signal engine and simulates target/stop hits — the source of truth for
    tuning. Query params:
      asset_id   — backtest a single asset (optional)
      timeframe  — required, e.g. 1h
      days       — history depth (default 60)
      market     — restrict portfolio backtest to one market (optional)
      limit      — max assets for portfolio backtest (default 15)
    Without asset_id it runs a portfolio backtest across active assets.
    """
    from app.services.backtest import run_backtest, backtest_portfolio

    timeframe = request.args.get("timeframe", "1h")
    days      = request.args.get("days", default=60, type=int)
    asset_id  = request.args.get("asset_id", type=int)
    symbol    = request.args.get("symbol", "").upper().strip()

    # Allow lookup by symbol string (used by the backtesting UI)
    if not asset_id and symbol:
        a = Asset.query.filter(Asset.symbol.ilike(symbol), Asset.is_active == True).first()
        if not a:
            return jsonify({"error": f"Asset '{symbol}' not found. Check the symbol and try again."}), 404
        asset_id = a.id

    if asset_id:
        asset = Asset.query.get_or_404(asset_id)
        result = run_backtest(asset, timeframe, days=days)
        # Normalise trade keys for the UI (add 'r' field)
        for t in result.get("trades_data", []):
            if "r" not in t and t.get("pnl_pct") is not None:
                t["r"] = round(t["pnl_pct"] / 100, 4)
        return jsonify(result), 200

    # Portfolio backtest — bounded to keep runtime reasonable.
    market = request.args.get("market")
    limit  = request.args.get("limit", default=15, type=int)
    q = Asset.query.filter_by(is_active=True)
    if market:
        q = q.filter_by(market=market)
    assets = q.order_by(Asset.market, Asset.symbol).limit(limit).all()

    return jsonify(backtest_portfolio(assets, timeframe, days=days)), 200


@signals_bp.route("/export/csv", methods=["GET"])
@login_required
def export_signals_csv():
    """Export live signals as CSV."""
    market      = request.args.get("market")
    timeframe   = request.args.get("timeframe")
    signal_type = request.args.get("signal_type")
    status      = request.args.get("status", "active")

    query = Signal.query.join(Asset)
    if market:
        query = query.filter(Asset.market == market)
    if timeframe:
        query = query.filter(Signal.timeframe == timeframe)
    if signal_type:
        query = query.filter(Signal.signal_type == signal_type)
    if status:
        query = query.filter(Signal.status == status)

    signals = query.order_by(Signal.generated_at.desc()).all()

    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(["Date","Asset","Market","Timeframe","Signal","Entry","Stop Loss",
                     "Target1","Target2","R:R","Confidence","Status","Reasoning"])
    for s in signals:
        writer.writerow([
            s.generated_at.strftime("%Y-%m-%d %H:%M") if s.generated_at else "",
            s.asset.symbol if s.asset else "",
            s.asset.market if s.asset else "",
            s.timeframe,
            s.signal_type,
            s.entry_price,
            s.stop_loss,
            s.target1,
            s.target2,
            round(s.risk_reward, 2) if s.risk_reward else "",
            round(s.confidence_score, 1) if s.confidence_score else "",
            s.status,
            s.reasoning or "",
        ])

    today = datetime.utcnow().strftime("%Y-%m-%d")
    return Response(
        buf.getvalue(),
        mimetype="text/csv",
        headers={"Content-Disposition": f"attachment; filename=signals_{today}.csv"},
    )


@signals_bp.route("/history/export/csv", methods=["GET"])
@login_required
def export_history_csv():
    """Export signal history as CSV."""
    records = SignalHistory.query.order_by(SignalHistory.closed_at.desc()).all()
    asset_ids = {r.asset_id for r in records}
    assets_map = {a.id: a for a in Asset.query.filter(Asset.id.in_(asset_ids)).all()}

    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(["Date","Asset","Market","Timeframe","Signal","Entry",
                     "Outcome","PnL%","Duration(min)","R:R Predicted"])
    for h in records:
        asset = assets_map.get(h.asset_id)
        # Approximate R:R from entry/stop_loss/target1
        predicted_rr = ""
        if h.entry_price and h.stop_loss and h.target1 and h.entry_price != h.stop_loss:
            predicted_rr = round(abs(h.target1 - h.entry_price) / abs(h.entry_price - h.stop_loss), 2)
        writer.writerow([
            h.closed_at.strftime("%Y-%m-%d %H:%M") if h.closed_at else "",
            asset.symbol if asset else "",
            asset.market if asset else "",
            h.timeframe,
            h.signal_type,
            h.entry_price,
            h.outcome,
            round(h.pnl_pct, 2) if h.pnl_pct is not None else "",
            h.duration_minutes or "",
            predicted_rr,
        ])

    today = datetime.utcnow().strftime("%Y-%m-%d")
    return Response(
        buf.getvalue(),
        mimetype="text/csv",
        headers={"Content-Disposition": f"attachment; filename=signal_history_{today}.csv"},
    )
