"""add regime column to signals

Revision ID: 0e70566be9f5
Revises: d26fd8b070f0
Create Date: 2026-07-04 15:40:58.835718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e70566be9f5'
down_revision = 'd26fd8b070f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regime', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_column('regime')

    # ### end Alembic commands ###
