"""add mtf_watch_configs table

Note: `flask db migrate` also reported pre-existing drift on the `brokers`
table (a name index modelled as a unique constraint), same as the drift
noted in 6b381ae52526/8aee6023225f -- deliberately NOT included here for the
same reason (unrelated to this change, and its autogenerated downgrade uses
drop_constraint(None, ...) with no constraint name to act on).

Revision ID: 2f5214649a5f
Revises: 8aee6023225f
Create Date: 2026-08-29 09:21:10.292893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f5214649a5f'
down_revision = '8aee6023225f'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('mtf_watch_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbols', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mtf_watch_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mtf_watch_configs_user_id'), ['user_id'], unique=True)


def downgrade():
    with op.batch_alter_table('mtf_watch_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mtf_watch_configs_user_id'))

    op.drop_table('mtf_watch_configs')
