"""add alert_repeat to watchlist_items

Revision ID: 45cdcf9eb85e
Revises: eafc65485e3f
Create Date: 2026-07-11 17:53:36.572525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45cdcf9eb85e'
down_revision = 'eafc65485e3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alert_repeat', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.drop_column('alert_repeat')

    # ### end Alembic commands ###
