"""add indexes on watchlist_items.watchlist_id, portfolio_items.portfolio_id, economic_events.event_time

These three columns are the literal filter key of queries that already run
per-request or on a schedule (watchlist item lookups, portfolio item lookups,
and the economic-calendar window query), but were unindexed — so each degrades
to a sequential scan as the tables grow.

Note: `flask db migrate` also reported pre-existing drift on the `brokers`
table (a name index modelled as a unique constraint). That is unrelated to this
change and is deliberately NOT included here — mixing an unintended constraint
change into an index migration would make this irreversible in practice, and
the autogenerated downgrade for it used drop_constraint(None, ...), which has
no constraint name to act on and would fail. Left for a dedicated migration.

Revision ID: 6b381ae52526
Revises: 5e30c5719312
Create Date: 2026-08-28 20:23:41.553066

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '6b381ae52526'
down_revision = '5e30c5719312'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('economic_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_economic_events_event_time'), ['event_time'], unique=False)

    with op.batch_alter_table('portfolio_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_items_portfolio_id'), ['portfolio_id'], unique=False)

    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlist_items_watchlist_id'), ['watchlist_id'], unique=False)


def downgrade():
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_items_watchlist_id'))

    with op.batch_alter_table('portfolio_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_items_portfolio_id'))

    with op.batch_alter_table('economic_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_economic_events_event_time'))
