"""add index on user_asset_preferences.user_id

Revision ID: 6eb21ea78dfa
Revises: b8c9d0e1f2a3
Create Date: 2026-07-11 13:18:21.140093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eb21ea78dfa'
down_revision = 'b8c9d0e1f2a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_asset_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_asset_preferences_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_asset_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_asset_preferences_user_id'))

    # ### end Alembic commands ###
