"""add saved_screens table

Note: `flask db migrate` also reported pre-existing drift on the `brokers`
table (a name index modelled as a unique constraint), same as the drift
noted in 6b381ae52526 — deliberately NOT included here for the same reason
(unrelated to this change, and its autogenerated downgrade uses
drop_constraint(None, ...) with no constraint name to act on).

Revision ID: 8aee6023225f
Revises: 6b381ae52526
Create Date: 2026-08-28 21:57:13.860752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aee6023225f'
down_revision = '6b381ae52526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_screens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('asset_type', sa.String(length=30), nullable=False),
    sa.Column('combinator', sa.String(length=3), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_saved_screen_user_name')
    )
    with op.batch_alter_table('saved_screens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_screens_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_screens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_screens_user_id'))

    op.drop_table('saved_screens')
    # ### end Alembic commands ###
