"""initial schema

Revision ID: 9aa5558991b2
Revises: 
Create Date: 2026-07-01 21:29:32.805898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aa5558991b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_configs', schema=None) as batch_op:
        batch_op.alter_column('websocket_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('auth_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               existing_nullable=True,
               existing_server_default=sa.text("'api_key'"))
        batch_op.alter_column('is_default',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'active'"))
        batch_op.alter_column('connection_status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'unknown'"))

    with op.batch_alter_table('api_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_api_logs_config_time'))

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_audit_logs_created'))
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('backtests', schema=None) as batch_op:
        batch_op.alter_column('sortino_ratio',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('avg_bars_held',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('total_commission',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('total_slippage',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('commission_pct',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.1)'))
        batch_op.alter_column('slippage_pct',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.05)'))
        batch_op.alter_column('exit_reasons',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'"))

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_journal_user_date'))

    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_sys_logs_level_time'))
        batch_op.create_index(batch_op.f('ix_system_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_logs_level'), ['level'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('account_size',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(100000.0)'))
        batch_op.alter_column('risk_per_trade_pct',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(1.0)'))
        batch_op.alter_column('totp_secret',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('totp_enabled',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('totp_enabled',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('totp_secret',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('risk_per_trade_pct',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(1.0)'))
        batch_op.alter_column('account_size',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(100000.0)'))

    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_logs_level'))
        batch_op.drop_index(batch_op.f('ix_system_logs_created_at'))
        batch_op.create_index(batch_op.f('idx_sys_logs_level_time'), ['level', 'created_at'], unique=False)

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_journal_user_date'), ['user_id', 'trade_date'], unique=False)

    with op.batch_alter_table('backtests', schema=None) as batch_op:
        batch_op.alter_column('exit_reasons',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'"))
        batch_op.alter_column('slippage_pct',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.05)'))
        batch_op.alter_column('commission_pct',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.1)'))
        batch_op.alter_column('total_slippage',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('total_commission',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('avg_bars_held',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('sortino_ratio',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.create_index(batch_op.f('idx_audit_logs_created'), ['created_at'], unique=False)

    with op.batch_alter_table('api_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_api_logs_config_time'), ['api_config_id', 'created_at'], unique=False)

    with op.batch_alter_table('api_configs', schema=None) as batch_op:
        batch_op.alter_column('connection_status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'unknown'"))
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'active'"))
        batch_op.alter_column('is_default',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('auth_type',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'api_key'"))
        batch_op.alter_column('websocket_url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
