"""Add auto_generate_config table

Revision ID: bc7ace6eeac6
Revises: 9aa5558991b2
Create Date: 2026-07-02 21:54:09.438208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc7ace6eeac6'
down_revision = '9aa5558991b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_generate_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('running', sa.Boolean(), nullable=True),
    sa.Column('asset_ids', sa.JSON(), nullable=True),
    sa.Column('timeframes', sa.JSON(), nullable=True),
    sa.Column('signal_filter', sa.String(length=20), nullable=True),
    sa.Column('min_confidence', sa.Float(), nullable=True),
    sa.Column('max_per_run', sa.Integer(), nullable=True),
    sa.Column('interval_minutes', sa.Integer(), nullable=True),
    sa.Column('telegram_on_signal', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auto_generate_config')
    # ### end Alembic commands ###
