"""Add markets column to auto_generate_config

Revision ID: d26fd8b070f0
Revises: bc7ace6eeac6
Create Date: 2026-07-02 21:57:53.540359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd26fd8b070f0'
down_revision = 'bc7ace6eeac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auto_generate_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('markets', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auto_generate_config', schema=None) as batch_op:
        batch_op.drop_column('markets')

    # ### end Alembic commands ###
