"""add protective_orders table

Revision ID: eafc65485e3f
Revises: 1b45699f4ea6
Create Date: 2026-07-11 17:42:57.637048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eafc65485e3f'
down_revision = '1b45699f4ea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protective_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_item_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('trailing_enabled', sa.Boolean(), nullable=False),
    sa.Column('trailing_distance_pct', sa.Float(), nullable=True),
    sa.Column('high_water_mark', sa.Float(), nullable=True),
    sa.Column('auto_execute', sa.Boolean(), nullable=False),
    sa.Column('is_dry_run', sa.Boolean(), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_checked_price', sa.Float(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('trigger_price', sa.Float(), nullable=True),
    sa.Column('broker_order_result', sa.Text(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['portfolio_item_id'], ['portfolio_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('protective_orders', schema=None) as batch_op:
        batch_op.create_index('idx_protective_order_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_protective_orders_portfolio_item_id'), ['portfolio_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_protective_orders_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('protective_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_protective_orders_user_id'))
        batch_op.drop_index(batch_op.f('ix_protective_orders_portfolio_item_id'))
        batch_op.drop_index('idx_protective_order_status')

    op.drop_table('protective_orders')
    # ### end Alembic commands ###
